#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER $DB_USER_KEYCLOAK WITH PASSWORD '$DB_PASS_KEYCLOAK';
	CREATE DATABASE $DB_NAME_KEYCLOAK;
	GRANT ALL PRIVILEGES ON DATABASE $DB_NAME_KEYCLOAK TO $DB_USER_KEYCLOAK;
EOSQL
